<div class="page-header">
  <h1>Add</h1>
</div>
<form method="POST" action="<?php echo $block->getUrl('*/*/save')?>">
	<div class="form-group">
		<label>Name</label>
		<input type="text" class="form-control" name="name" placeholder="Enter name">
	</div>
	<div class="form-group">
		<label>Email address</label>
		<input type="email" class="form-control" name="email" placeholder="Enter email">
	</div>
	<div class="form-group">
		<label>Phone</label>
		<input type="phone" class="form-control" name="phone" placeholder="Enter phone">
	</div>
	<button type="submit" class="btn btn-primary">Save</button>
</form>