<div class="page-header">
  <h1>Edit</h1>
</div>
<form method="POST" action="<?php echo $block->getUrl('*/*/save/teacher_id/'.$block->getTeacher()['teacher_id'])?>">
	<div class="form-group">
		<label>Name</label>
		<input type="text" class="form-control" value="<?php echo $block->getTeacher()['teacher_name']?>" name="name" placeholder="Enter name">
	</div>
	<div class="form-group">
		<label>Email address</label>
		<input type="email" class="form-control" value="<?php echo $block->getTeacher()['teacher_email']?>" name="email" placeholder="Enter email">
	</div>
	<div class="form-group">
		<label>Phone</label>
		<input type="phone" class="form-control" value="<?php echo $block->getTeacher()['teacher_phone']?>" name="phone" placeholder="Enter phone">
	</div>
	<button type="submit" class="btn btn-primary">Save</button>
</form>